version: '3.7'
services:
  user-service:
    build: ./user-service/
    ports:
      - 8081:8081 
    depends_on:
      - mongodb
    networks:
      - db

  auth-service:
    build: ./auth-service/
    ports:
      - 8082:8082 
    depends_on:
      - mongodb
      - cache
    networks:
      - db

  api-gateway:
    build: ./api-gateway/
    ports:
      - 8080:8080
    depends_on:
      - user-service
      - auth-service
    networks:
      - db

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafi
      - MONGO_INITDB_ROOT_PASSWORD=testrafipassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - db

  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - db

volumes:
  mongodb_data_container:
  cache:

networks:
  db:
    driver: bridge
