apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/db: "true"
        io.kompose.service: cache
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "20"
            - "1"
            - --loglevel
            - warning
            - --requirepass
            - eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
          image: redis:7.0-alpine
          name: cache
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: cache
      restartPolicy: Always
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
status: {}
